# Create YAML for services
# File create on October 2022
# Owner Kittipak Yamsri; kittipak.y@tgetting.co.th, kittipak.y@gmail.com
# Reference https://docs.docker.com/, https://prometheus.io/
#------------------------------------------------------------------------
version: '3.6'

networks:
  monitor-net:
    driver: bridge
volumes:
    prometheus_data: {}
    grafana_data: {}

services:
# Core architecture
  prometheus:
    # image: prom/prometheus:latest  >> If need to alway last version
    image: prom/prometheus:v2.39.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/webprometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    #  - '--storage.tsdb.retention.time=200h'
      - '--storage.tsdb.retention.time=14d'
      - '--web.enable-lifecycle'
    ports:
      - 1155:9090
    restart: unless-stopped
    networks:
      - monitor-net
 # Exporter data from host  
  nodeexporter:
    # image: prom/node-exporter:latest >> If need to alway last version
    image: prom/node-exporter:v1.4.0
    container_name: nodeexporter
    volumes:
      - ./prometheus:/etc/prometheus
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--web.config=/etc/prometheus/webnodeexporter.yml'
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 1166:9100
    restart: unless-stopped
    networks:
      - monitor-net

